nodeLinker: node-modules

packageExtensions:
  bootstrap@*:
    peerDependenciesMeta:
      jquery:
        optional: true
  portal-vue@*:
    peerDependenciesMeta:
      vue:
        optional: true

yarnPath: .yarn/releases/yarn-3.6.3.cjs
